const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'word_bank.js');
let content = fs.readFileSync(filePath, 'utf8');

const newWords = [
  // 多益必考 (40)
  { en: "accommodate", zh: "容納；提供住宿", cat: "多益必考" },
  { en: "accomplish", zh: "完成；實現", cat: "多益必考" },
  { en: "agenda", zh: "議程", cat: "多益必考" },
  { en: "allocate", zh: "分配；分派", cat: "多益必考" },
  { en: "alternative", zh: "替代方案", cat: "多益必考" },
  { en: "amend", zh: "修改；修訂", cat: "多益必考" },
  { en: "anonymous", zh: "匿名的", cat: "多益必考" },
  { en: "anticipate", zh: "預期；期望", cat: "多益必考" },
  { en: "appraise", zh: "評估；評價", cat: "多益必考" },
  { en: "asset", zh: "資產", cat: "多益必考" },
  { en: "assign", zh: "指派", cat: "多益必考" },
  { en: "authorize", zh: "授權；批准", cat: "多益必考" },
  { en: "bankruptcy", zh: "破產", cat: "多益必考" },
  { en: "benchmark", zh: "基準；水準點", cat: "多益必考" },
  { en: "bid", zh: "出價；投標", cat: "多益必考" },
  { en: "candidate", zh: "候選人", cat: "多益必考" },
  { en: "capacity", zh: "容量；能力", cat: "多益必考" },
  { en: "certificate", zh: "證書", cat: "多益必考" },
  { en: "collaborate", zh: "合作", cat: "多益必考" },
  { en: "commute", zh: "通勤", cat: "多益必考" },
  { en: "compensate", zh: "補償；賠償", cat: "多益必考" },
  { en: "complimentary", zh: "免費的；贈送的", cat: "多益必考" },
  { en: "comprehensive", zh: "全面的；詳盡的", cat: "多益必考" },
  { en: "compromise", zh: "妥協；折衷", cat: "多益必考" },
  { en: "confidential", zh: "機密的", cat: "多益必考" },
  { en: "consecutive", zh: "連續的", cat: "多益必考" },
  { en: "consensus", zh: "共識", cat: "多益必考" },
  { en: "coordinate", zh: "協調", cat: "多益必考" },
  { en: "corporate", zh: "公司的；企業的", cat: "多益必考" },
  { en: "crucial", zh: "關鍵的；重要的", cat: "多益必考" },
  { en: "deadline", zh: "截止日期", cat: "多益必考" },
  { en: "deficit", zh: "赤字；虧損", cat: "多益必考" },
  { en: "delegate", zh: "委派；代表", cat: "多益必考" },
  { en: "demonstrate", zh: "示範；證明", cat: "多益必考" },
  { en: "deteriorate", zh: "惡化", cat: "多益必考" },
  { en: "discrepancy", zh: "差異；不一致", cat: "多益必考" },
  { en: "dispatch", zh: "派遣；發送", cat: "多益必考" },
  { en: "distribute", zh: "分發；分配", cat: "多益必考" },
  { en: "drastically", zh: "大幅地；徹底地", cat: "多益必考" },
  { en: "eligible", zh: "有資格的", cat: "多益必考" },
  // 雅思常見 (30)
  { en: "abundant", zh: "豐富的；充裕的", cat: "雅思常見" },
  { en: "acquire", zh: "獲得；取得", cat: "雅思常見" },
  { en: "adapt", zh: "適應", cat: "雅思常見" },
  { en: "adequate", zh: "足夠的；適當的", cat: "雅思常見" },
  { en: "advocate", zh: "提倡；擁護", cat: "雅思常見" },
  { en: "alleviate", zh: "減輕；緩和", cat: "雅思常見" },
  { en: "ambiguous", zh: "模稜兩可的", cat: "雅思常見" },
  { en: "analyze", zh: "分析", cat: "雅思常見" },
  { en: "approach", zh: "方法；接近", cat: "雅思常見" },
  { en: "assess", zh: "評估", cat: "雅思常見" },
  { en: "assume", zh: "假設；認為", cat: "雅思常見" },
  { en: "attain", zh: "達到；獲得", cat: "雅思常見" },
  { en: "beneficial", zh: "有益的", cat: "雅思常見" },
  { en: "capable", zh: "有能力的", cat: "雅思常見" },
  { en: "clarify", zh: "澄清；說明", cat: "雅思常見" },
  { en: "coherent", zh: "連貫的；有條理的", cat: "雅思常見" },
  { en: "coincide", zh: "同時發生；巧合", cat: "雅思常見" },
  { en: "collapse", zh: "倒塌；崩潰", cat: "雅思常見" },
  { en: "commence", zh: "開始", cat: "雅思常見" },
  { en: "compatible", zh: "相容的；合得來的", cat: "雅思常見" },
  { en: "compile", zh: "編譯；收集", cat: "雅思常見" },
  { en: "conceive", zh: "構思；想像", cat: "雅思常見" },
  { en: "conclude", zh: "得出結論；結束", cat: "雅思常見" },
  { en: "conduct", zh: "執行；進行", cat: "雅思常見" },
  { en: "confine", zh: "限制；侷限", cat: "雅思常見" },
  { en: "conflict", zh: "衝突；矛盾", cat: "雅思常見" },
  { en: "consequence", zh: "後果；結果", cat: "雅思常見" },
  { en: "consistent", zh: "一致的", cat: "雅思常見" },
  { en: "constitute", zh: "構成；組成", cat: "雅思常見" },
  { en: "consume", zh: "消耗；消費", cat: "雅思常見" },
  // 職場溝通 (25)
  { en: "attachment", zh: "附件", cat: "職場溝通" },
  { en: "briefing", zh: "簡報", cat: "職場溝通" },
  { en: "brainstorm", zh: "腦力激盪", cat: "職場溝通" },
  { en: "clarification", zh: "澄清", cat: "職場溝通" },
  { en: "colleague", zh: "同事", cat: "職場溝通" },
  { en: "feedback", zh: "回饋", cat: "職場溝通" },
  { en: "follow-up", zh: "後續追蹤", cat: "職場溝通" },
  { en: "guideline", zh: "指南；準則", cat: "職場溝通" },
  { en: "implement", zh: "實施；執行", cat: "職場溝通" },
  { en: "initiative", zh: "主動性；倡議", cat: "職場溝通" },
  { en: "inquiry", zh: "詢問", cat: "職場溝通" },
  { en: "milestone", zh: "里程碑", cat: "職場溝通" },
  { en: "negotiate", zh: "談判；協商", cat: "職場溝通" },
  { en: "objective", zh: "目標", cat: "職場溝通" },
  { en: "onboard", zh: "使入職", cat: "職場溝通" },
  { en: "overview", zh: "概述", cat: "職場溝通" },
  { en: "pending", zh: "待處理的", cat: "職場溝通" },
  { en: "prioritize", zh: "優先處理", cat: "職場溝通" },
  { en: "proposal", zh: "提案", cat: "職場溝通" },
  { en: "recruit", zh: "招募", cat: "職場溝通" },
  { en: "reschedule", zh: "重新安排", cat: "職場溝通" },
  { en: "strategy", zh: "策略", cat: "職場溝通" },
  { en: "supervisor", zh: "主管", cat: "職場溝通" },
  { en: "update", zh: "更新進度", cat: "職場溝通" },
  { en: "workload", zh: "工作量", cat: "職場溝通" },
  // 日常對話 (20)
  { en: "awesome", zh: "太棒了", cat: "日常對話" },
  { en: "bother", zh: "打擾", cat: "日常對話" },
  { en: "cancel", zh: "取消", cat: "日常對話" },
  { en: "casual", zh: "休閒的；隨便的", cat: "日常對話" },
  { en: "chat", zh: "聊天", cat: "日常對話" },
  { en: "chill", zh: "放鬆", cat: "日常對話" },
  { en: "crazy", zh: "瘋狂的", cat: "日常對話" },
  { en: "definitely", zh: "絕對；當然", cat: "日常對話" },
  { en: "exactly", zh: "完全正確", cat: "日常對話" },
  { en: "exhausted", zh: "筋疲力盡的", cat: "日常對話" },
  { en: "figure", zh: "想出；理解", cat: "日常對話" },
  { en: "hang", zh: "閒晃；等待", cat: "日常對話" },
  { en: "hilarious", zh: "極好笑的", cat: "日常對話" },
  { en: "kidding", zh: "開玩笑", cat: "日常對話" },
  { en: "literally", zh: "不誇張地；字面上地", cat: "日常對話" },
  { en: "obvious", zh: "明顯的", cat: "日常對話" },
  { en: "probably", zh: "大概；可能", cat: "日常對話" },
  { en: "recommend", zh: "推薦", cat: "日常對話" },
  { en: "ridiculous", zh: "荒謬的", cat: "日常對話" },
  { en: "weird", zh: "奇怪的", cat: "日常對話" }
];

const newPhrases = [
  // 多益必考 (15)
  { en: "abide by", zh: "遵守", cat: "多益必考" },
  { en: "account for", zh: "解釋；佔...比例", cat: "多益必考" },
  { en: "in terms of", zh: "就...而言", cat: "多益必考" },
  { en: "in charge of", zh: "負責", cat: "多益必考" },
  { en: "prior to", zh: "在...之前", cat: "多益必考" },
  { en: "take into consideration", zh: "考慮進去", cat: "多益必考" },
  { en: "comply with", zh: "遵守；服從", cat: "多益必考" },
  { en: "be subject to", zh: "受...控制；易遭受...", cat: "多益必考" },
  { en: "rule out", zh: "排除", cat: "多益必考" },
  { en: "turn down", zh: "拒絕", cat: "多益必考" },
  { en: "look into", zh: "調查", cat: "多益必考" },
  { en: "fill in for", zh: "代理；替代", cat: "多益必考" },
  { en: "keep track of", zh: "記錄；追蹤", cat: "多益必考" },
  { en: "rely on", zh: "依賴", cat: "多益必考" },
  { en: "come up with", zh: "想出", cat: "多益必考" },
  // 雅思常見 (10)
  { en: "play a crucial role in", zh: "在...扮演關鍵角色", cat: "雅思常見" },
  { en: "stem from", zh: "源自於", cat: "雅思常見" },
  { en: "shed light on", zh: "闡明；解釋", cat: "雅思常見" },
  { en: "boil down to", zh: "歸結於", cat: "雅思常見" },
  { en: "take for granted", zh: "視為理所當然", cat: "雅思常見" },
  { en: "give rise to", zh: "引起；導致", cat: "雅思常見" },
  { en: "be prone to", zh: "傾向於；易於", cat: "雅思常見" },
  { en: "bear in mind", zh: "記住", cat: "雅思常見" },
  { en: "pave the way for", zh: "為...鋪路", cat: "雅思常見" },
  { en: "cope with", zh: "處理；應付", cat: "雅思常見" },
  // 職場溝通 (10)
  { en: "touch base", zh: "聯繫；跟進", cat: "職場溝通" },
  { en: "get back to", zh: "回覆", cat: "職場溝通" },
  { en: "bear with me", zh: "請耐心等我一下", cat: "職場溝通" },
  { en: "bring up", zh: "提出", cat: "職場溝通" },
  { en: "wrap up", zh: "結束；總結", cat: "職場溝通" },
  { en: "move forward", zh: "向前邁進", cat: "職場溝通" },
  { en: "keep someone in the loop", zh: "讓某人了解情況", cat: "職場溝通" },
  { en: "on the same page", zh: "達成共識", cat: "職場溝通" },
  { en: "point out", zh: "指出", cat: "職場溝通" },
  { en: "sort out", zh: "解決；整理", cat: "職場溝通" },
  // 日常對話 (10)
  { en: "hang out", zh: "出去玩", cat: "日常對話" },
  { en: "catch up", zh: "敘舊；趕上", cat: "日常對話" },
  { en: "never mind", zh: "沒關係；算了", cat: "日常對話" },
  { en: "take it easy", zh: "放輕鬆", cat: "日常對話" },
  { en: "make sense", zh: "有道理", cat: "日常對話" },
  { en: "figure out", zh: "想出；弄清楚", cat: "日常對話" },
  { en: "show up", zh: "出現", cat: "日常對話" },
  { en: "turn out", zh: "結果是", cat: "日常對話" },
  { en: "by the way", zh: "順帶一提", cat: "日常對話" },
  { en: "look forward to", zh: "期待", cat: "日常對話" }
];

const newSentences = [
  // 多益必考 (10)
  { en: "Please make sure to submit the report before the deadline.", zh: "請務必在截止日期前提交報告。", cat: "多益必考" },
  { en: "The company announced a significant increase in profits this quarter.", zh: "公司宣布本季度利潤大幅增長。", cat: "多益必考" },
  { en: "All employees are required to attend the mandatory training session.", zh: "所有員工都必須參加強制性的培訓課程。", cat: "多益必考" },
  { en: "We apologize for any inconvenience this may cause.", zh: "對於這可能造成的任何不便，我們深表歉意。", cat: "多益必考" },
  { en: "The meeting has been postponed due to unforeseen circumstances.", zh: "由於不可預見的情況，會議已延期。", cat: "多益必考" },
  { en: "Please review the attached document and let me know if you have any questions.", zh: "請查閱附件文件，如有任何問題請讓我知道。", cat: "多益必考" },
  { en: "Our customer service representatives are available 24/7 to assist you.", zh: "我們的客服代表全天候為您提供協助。", cat: "多益必考" },
  { en: "The new policy will be implemented starting next month.", zh: "新政策將從下個月開始實施。", cat: "多益必考" },
  { en: "We are currently looking for a qualified candidate to fill the position.", zh: "我們目前正在尋找合格的候選人來填補該職位。", cat: "多益必考" },
  { en: "Thank you for your prompt response and cooperation.", zh: "感謝您的及時回覆和合作。", cat: "多益必考" },
  // 雅思常見 (8)
  { en: "It is widely believed that education plays a crucial role in society.", zh: "人們普遍認為教育在社會中扮演著關鍵角色。", cat: "雅思常見" },
  { en: "There is a growing concern about the impact of climate change.", zh: "人們對氣候變遷的影響日益關注。", cat: "雅思常見" },
  { en: "One of the main advantages of this approach is its efficiency.", zh: "這種方法的主要優點之一是它的效率。", cat: "雅思常見" },
  { en: "To tackle this issue, the government needs to implement stricter regulations.", zh: "為了解決這個問題，政府需要實施更嚴格的規定。", cat: "雅思常見" },
  { en: "The data suggests a significant correlation between the two variables.", zh: "數據顯示這兩個變數之間存在顯著的相關性。", cat: "雅思常見" },
  { en: "In conclusion, the benefits outweigh the drawbacks.", zh: "總而言之，利大於弊。", cat: "雅思常見" },
  { en: "This phenomenon can be attributed to several underlying factors.", zh: "這種現象可以歸因於幾個潛在因素。", cat: "雅思常見" },
  { en: "However, critics argue that this policy may have negative consequences.", zh: "然而，批評者認為這項政策可能會有負面後果。", cat: "雅思常見" },
  // 職場溝通 (8)
  { en: "Could you please send me the latest version of the presentation?", zh: "可以請你寄給我最新版本的簡報嗎？", cat: "職場溝通" },
  { en: "I'll touch base with you later this week to discuss the project.", zh: "我這週晚些時候會和你聯繫討論這個專案。", cat: "職場溝通" },
  { en: "Let's schedule a meeting to go over the details.", zh: "我們安排個會議來詳細討論吧。", cat: "職場溝通" },
  { en: "Please keep me in the loop regarding any updates.", zh: "如有任何更新，請讓我知道。", cat: "職場溝通" },
  { en: "I'm writing to follow up on the email I sent yesterday.", zh: "我寫信來是為了跟進我昨天寄出的電子郵件。", cat: "職場溝通" },
  { en: "Could you clarify what you mean by that?", zh: "可以請你澄清一下你的意思嗎？", cat: "職場溝通" },
  { en: "Let's make sure we are all on the same page before moving forward.", zh: "在繼續之前，我們要確定大家的認知是一致的。", cat: "職場溝通" },
  { en: "I'd appreciate it if you could provide some feedback on my proposal.", zh: "如果你能對我的提案提供一些回饋，我會非常感激。", cat: "職場溝通" },
  // 日常對話 (8)
  { en: "What are you up to this weekend?", zh: "你這個週末要做什麼？", cat: "日常對話" },
  { en: "It's been a long time! We should definitely catch up soon.", zh: "好久不見！我們一定要找時間敘舊。", cat: "日常對話" },
  { en: "I totally agree with you on that.", zh: "在那一點上我完全同意你。", cat: "日常對話" },
  { en: "Don't worry about it, it's not a big deal.", zh: "別擔心，這沒什麼大不了的。", cat: "日常對話" },
  { en: "Can you give me a hand with this?", zh: "你可以幫我一下這個嗎？", cat: "日常對話" },
  { en: "I'm exhausted, I just want to chill at home tonight.", zh: "我累壞了，今晚只想待在家放鬆。", cat: "日常對話" },
  { en: "That makes a lot of sense.", zh: "那很有道理。", cat: "日常對話" },
  { en: "Let me know if you need anything else.", zh: "如果你還需要什麼，請讓我知道。", cat: "日常對話" }
];

function convertToJsonStr(items) {
  return items.map(item => `  {\n    "en": "${item.en}",\n    "zh": "${item.zh}",\n    "cat": "${item.cat}"\n  }`).join(',\n');
}

const wordsStr = convertToJsonStr(newWords);
const phrasesStr = convertToJsonStr(newPhrases);
const sentencesStr = convertToJsonStr(newSentences);

content = content.replace(/\],\s*phrase:\s*\[/, ',\n' + wordsStr + '\n],\n  phrase: [');
content = content.replace(/\],\s*sentence:\s*\[/, ',\n' + phrasesStr + '\n],\n  sentence: [');
content = content.replace(/\]\s*\}\s*;\s*$/, ',\n' + sentencesStr + '\n]\n};');

fs.writeFileSync(filePath, content, 'utf8');
console.log('Successfully appended new items to word_bank.js');
