const WORD_BANK = {
  word: [
    // 旅遊
    {en:'passport', zh:'護照', cat:'旅遊'},
    {en:'luggage', zh:'行李', cat:'旅遊'},
    {en:'flight', zh:'航班', cat:'旅遊'},
    {en:'customs', zh:'海關', cat:'旅遊'},
    {en:'destination', zh:'目的地', cat:'旅遊'},
    {en:'souvenir', zh:'紀念品', cat:'旅遊'},
    {en:'accommodation', zh:'住宿', cat:'旅遊'},
    {en:'reservation', zh:'預約', cat:'旅遊'},
    {en:'terminal', zh:'航廈', cat:'旅遊'},
    {en:'departure', zh:'出發', cat:'旅遊'},
    {en:'arrival', zh:'抵達', cat:'旅遊'},
    {en:'sightseeing', zh:'觀光', cat:'旅遊'},
    {en:'delay', zh:'延誤', cat:'旅遊'},
    {en:'embassy', zh:'大使館', cat:'旅遊'},
    {en:'itinerary', zh:'行程表', cat:'旅遊'},

    // 美食
    {en:'appetizer', zh:'開胃菜', cat:'美食'},
    {en:'main course', zh:'主菜', cat:'美食'},
    {en:'dessert', zh:'點心', cat:'美食'},
    {en:'beverage', zh:'飲料', cat:'美食'},
    {en:'menu', zh:'菜單', cat:'美食'},
    {en:'receipt', zh:'收據', cat:'美食'},
    {en:'tip', zh:'小費', cat:'美食'},
    {en:'buffet', zh:'自助餐', cat:'美食'},
    {en:'vegetarian', zh:'素食', cat:'美食'},
    {en:'seafood', zh:'海鮮', cat:'美食'},
    {en:'cutlery', zh:'餐具', cat:'美食'},
    {en:'flavor', zh:'風味', cat:'美食'},
    {en:'ingredient', zh:'食材', cat:'美食'},
    {en:'chef', zh:'主廚', cat:'美食'},
    {en:'cuisine', zh:'料理', cat:'美食'},

    // 科技
    {en:'algorithm', zh:'演算法', cat:'科技'},
    {en:'software', zh:'軟體', cat:'科技'},
    {en:'hardware', zh:'硬體', cat:'科技'},
    {en:'database', zh:'資料庫', cat:'科技'},
    {en:'network', zh:'網路', cat:'科技'},
    {en:'cybersecurity', zh:'資訊安全', cat:'科技'},
    {en:'application', zh:'應用程式', cat:'科技'},
    {en:'browser', zh:'瀏覽器', cat:'科技'},
    {en:'server', zh:'伺服器', cat:'科技'},
    {en:'connection', zh:'連線', cat:'科技'},
    {en:'encryption', zh:'加密', cat:'科技'},
    {en:'feature', zh:'功能', cat:'科技'},
    {en:'device', zh:'裝置', cat:'科技'},
    {en:'update', zh:'更新', cat:'科技'},
    {en:'storage', zh:'儲存空間', cat:'科技'},

    // 健康
    {en:'nutrition', zh:'營養', cat:'健康'},
    {en:'symptom', zh:'症狀', cat:'健康'},
    {en:'prescription', zh:'處方籤', cat:'健康'},
    {en:'diagnosis', zh:'診斷', cat:'健康'},
    {en:'workout', zh:'運動健身', cat:'健康'},
    {en:'muscle', zh:'肌肉', cat:'健康'},
    {en:'calorie', zh:'卡路里', cat:'健康'},
    {en:'pharmacy', zh:'藥局', cat:'健康'},
    {en:'allergy', zh:'過敏', cat:'健康'},
    {en:'recovery', zh:'恢復', cat:'健康'},
    {en:'immunity', zh:'免疫力', cat:'健康'},
    {en:'fatigue', zh:'疲勞', cat:'健康'},
    {en:'hydrated', zh:'水分充足的', cat:'健康'},
    {en:'stamina', zh:'耐力', cat:'健康'},
    {en:'physician', zh:'醫師', cat:'健康'},

    // 情緒
    {en:'anxiety', zh:'焦慮', cat:'情緒'},
    {en:'delight', zh:'喜悅', cat:'情緒'},
    {en:'frustration', zh:'挫折', cat:'情緒'},
    {en:'empathy', zh:'同理心', cat:'情緒'},
    {en:'enthusiasm', zh:'熱情', cat:'情緒'},
    {en:'grief', zh:'悲傷', cat:'情緒'},
    {en:'jealousy', zh:'嫉妒', cat:'情緒'},
    {en:'relief', zh:'放鬆', cat:'情緒'},
    {en:'surprise', zh:'驚喜', cat:'情緒'},
    {en:'confidence', zh:'信心', cat:'情緒'},
    {en:'anger', zh:'憤怒', cat:'情緒'},
    {en:'gratitude', zh:'感恩', cat:'情緒'},
    {en:'loneliness', zh:'孤獨', cat:'情緒'},
    {en:'embarrassment', zh:'尷尬', cat:'情緒'},
    {en:'optimism', zh:'樂觀', cat:'情緒'},

    // 日常
    {en:'commute', zh:'通勤', cat:'日常'},
    {en:'routine', zh:'例行公事', cat:'日常'},
    {en:'errand', zh:'雜事', cat:'日常'},
    {en:'chore', zh:'家務', cat:'日常'},
    {en:'alarm', zh:'鬧鐘', cat:'日常'},
    {en:'appointment', zh:'約會', cat:'日常'},
    {en:'laundry', zh:'洗滌物', cat:'日常'},
    {en:'schedule', zh:'行程', cat:'日常'},
    {en:'neighbor', zh:'鄰居', cat:'日常'},
    {en:'appliance', zh:'家電', cat:'日常'},
    {en:'balcony', zh:'陽台', cat:'日常'},
    {en:'grocery', zh:'雜貨', cat:'日常'},
    {en:'leisure', zh:'休閒', cat:'日常'},
    {en:'trash', zh:'垃圾', cat:'日常'},
    {en:'habit', zh:'習慣', cat:'日常'},

    // 購物
    {en:'discount', zh:'折扣', cat:'購物'},
    {en:'coupon', zh:'優惠券', cat:'購物'},
    {en:'refund', zh:'退款', cat:'購物'},
    {en:'exchange', zh:'更換', cat:'購物'},
    {en:'bargain', zh:'便宜貨', cat:'購物'},
    {en:'cashier', zh:'結帳員', cat:'購物'},
    {en:'checkout', zh:'結帳台', cat:'購物'},
    {en:'fitting room', zh:'試衣間', cat:'購物'},
    {en:'receipt', zh:'發票', cat:'購物'},
    {en:'warranty', zh:'保固', cat:'購物'},
    {en:'cart', zh:'購物車', cat:'購物'},
    {en:'price tag', zh:'標價籤', cat:'購物'},
    {en:'aisle', zh:'走道', cat:'購物'},
    {en:'inventory', zh:'庫存', cat:'購物'},
    {en:'customer', zh:'顧客', cat:'購物'},

    // 天氣
    {en:'forecast', zh:'預報', cat:'天氣'},
    {en:'humidity', zh:'濕度', cat:'天氣'},
    {en:'temperature', zh:'溫度', cat:'天氣'},
    {en:'thunderstorm', zh:'雷陣雨', cat:'天氣'},
    {en:'drizzle', zh:'細雨', cat:'天氣'},
    {en:'blizzard', zh:'暴風雪', cat:'天氣'},
    {en:'drought', zh:'乾旱', cat:'天氣'},
    {en:'breeze', zh:'微風', cat:'天氣'},
    {en:'climate', zh:'氣候', cat:'天氣'},
    {en:'degree', zh:'度數', cat:'天氣'},
    {en:'heatwave', zh:'熱浪', cat:'天氣'},
    {en:'typhoon', zh:'颱風', cat:'天氣'},
    {en:'fog', zh:'霧', cat:'天氣'},
    {en:'sunshine', zh:'陽光', cat:'天氣'},
    {en:'precipitation', zh:'降水量', cat:'天氣'},

    // 娛樂
    {en:'concert', zh:'演唱會', cat:'娛樂'},
    {en:'exhibition', zh:'展覽', cat:'娛樂'},
    {en:'performance', zh:'表演', cat:'娛樂'},
    {en:'audience', zh:'觀眾', cat:'娛樂'},
    {en:'ticket', zh:'門票', cat:'娛樂'},
    {en:'cinema', zh:'電影院', cat:'娛樂'},
    {en:'festival', zh:'節慶', cat:'娛樂'},
    {en:'album', zh:'專輯', cat:'娛樂'},
    {en:'episode', zh:'集數', cat:'娛樂'},
    {en:'director', zh:'導演', cat:'娛樂'},
    {en:'genre', zh:'類型', cat:'娛樂'},
    {en:'platform', zh:'平台', cat:'娛樂'},
    {en:'streaming', zh:'串流', cat:'娛樂'},
    {en:'venue', zh:'場地', cat:'娛樂'},
    {en:'rehearsal', zh:'彩排', cat:'娛樂'},

    // 運動
    {en:'athlete', zh:'運動員', cat:'運動'},
    {en:'tournament', zh:'錦標賽', cat:'運動'},
    {en:'championship', zh:'冠軍賽', cat:'運動'},
    {en:'referee', zh:'裁判', cat:'運動'},
    {en:'stadium', zh:'體育場', cat:'運動'},
    {en:'penalty', zh:'罰則', cat:'運動'},
    {en:'score', zh:'分數', cat:'運動'},
    {en:'defense', zh:'防守', cat:'運動'},
    {en:'offense', zh:'進攻', cat:'運動'},
    {en:'stamina', zh:'耐力', cat:'運動'},
    {en:'trophy', zh:'獎盃', cat:'運動'},
    {en:'marathon', zh:'馬拉松', cat:'運動'},
    {en:'victory', zh:'勝利', cat:'運動'},
    {en:'opponent', zh:'對手', cat:'運動'},
    {en:'coach', zh:'教練', cat:'運動'},

    // 教育
    {en:'curriculum', zh:'課程安排', cat:'教育'},
    {en:'tuition', zh:'學費', cat:'教育'},
    {en:'assignment', zh:'作業', cat:'教育'},
    {en:'lecture', zh:'講座', cat:'教育'},
    {en:'professor', zh:'教授', cat:'教育'},
    {en:'degree', zh:'學位', cat:'教育'},
    {en:'scholarship', zh:'獎學金', cat:'教育'},
    {en:'semester', zh:'學期', cat:'教育'},
    {en:'campus', zh:'校園', cat:'教育'},
    {en:'thesis', zh:'論文', cat:'教育'},
    {en:'syllabus', zh:'課程大綱', cat:'教育'},
    {en:'exam', zh:'考試', cat:'教育'},
    {en:'library', zh:'圖書館', cat:'教育'},
    {en:'research', zh:'研究', cat:'教育'},
    {en:'graduation', zh:'畢業', cat:'教育'},

    // 職場
    {en:'colleague', zh:'同事', cat:'職場'},
    {en:'promotion', zh:'升遷', cat:'職場'},
    {en:'salary', zh:'薪水', cat:'職場'},
    {en:'deadline', zh:'截止日期', cat:'職場'},
    {en:'agenda', zh:'議程', cat:'職場'},
    {en:'resume', zh:'履歷', cat:'職場'},
    {en:'interview', zh:'面試', cat:'職場'},
    {en:'feedback', zh:'回饋', cat:'職場'},
    {en:'performance', zh:'績效', cat:'職場'},
    {en:'workflow', zh:'工作流程', cat:'職場'},
    {en:'strategy', zh:'策略', cat:'職場'},
    {en:'department', zh:'部門', cat:'職場'},
    {en:'supervisor', zh:'主管', cat:'職場'},
    {en:'contract', zh:'合約', cat:'職場'},
    {en:'milestone', zh:'里程碑', cat:'職場'},

    // 環境
    {en:'conservation', zh:'保護', cat:'環境'},
    {en:'pollution', zh:'污染', cat:'環境'},
    {en:'ecosystem', zh:'生態系統', cat:'環境'},
    {en:'renewable', zh:'可再生的', cat:'環境'},
    {en:'biodiversity', zh:'生物多樣性', cat:'環境'},
    {en:'sustainability', zh:'永續性', cat:'環境'},
    {en:'emissions', zh:'排放物', cat:'環境'},
    {en:'recycling', zh:'回收', cat:'環境'},
    {en:'habitat', zh:'棲息地', cat:'環境'},
    {en:'footprint', zh:'碳足跡', cat:'環境'},
    {en:'deforestation', zh:'森林砍伐', cat:'環境'},
    {en:'solar', zh:'太陽能的', cat:'環境'},
    {en:'resource', zh:'資源', cat:'環境'},
    {en:'contamination', zh:'污染', cat:'環境'},
    {en:'ecology', zh:'生態學', cat:'環境'}
  ],
  phrase: [
    // 旅遊
    {en:'check in', zh:'辦理入住', cat:'旅遊'},
    {en:'check out', zh:'辦理退房', cat:'旅遊'},
    {en:'carry-on bag', zh:'隨身行李', cat:'旅遊'},
    {en:'duty-free shop', zh:'免稅店', cat:'旅遊'},
    {en:'boarding gate', zh:'登機門', cat:'旅遊'},
    {en:'travel agency', zh:'旅行社', cat:'旅遊'},
    {en:'round trip', zh:'雙程往返', cat:'旅遊'},
    {en:'one way', zh:'單程', cat:'旅遊'},
    {en:'lost and found', zh:'失物招領處', cat:'旅遊'},
    {en:'room service', zh:'客房服務', cat:'旅遊'},

    // 美食
    {en:'table for two', zh:'兩人桌', cat:'美食'},
    {en:'chef\'s special', zh:'主廚特餐', cat:'美食'},
    {en:'side dish', zh:'配菜', cat:'美食'},
    {en:'take out', zh:'外帶', cat:'美食'},
    {en:'dine in', zh:'內用', cat:'美食'},
    {en:'full course', zh:'全套餐', cat:'美食'},
    {en:'sparkling water', zh:'氣泡水', cat:'美食'},
    {en:'daily special', zh:'今日特餐', cat:'美食'},
    {en:'rare, medium, or well-done', zh:'三分、五分或全熟', cat:'美食'},
    {en:'split the bill', zh:'分開結帳', cat:'美食'},

    // 科技
    {en:'artificial intelligence', zh:'人工智慧', cat:'科技'},
    {en:'machine learning', zh:'機器學習', cat:'科技'},
    {en:'cloud computing', zh:'雲端運算', cat:'科技'},
    {en:'user interface', zh:'使用者介面', cat:'科技'},
    {en:'virtual reality', zh:'虛擬實境', cat:'科技'},
    {en:'data privacy', zh:'資料隱私', cat:'科技'},
    {en:'operating system', zh:'作業系統', cat:'科技'},
    {en:'source code', zh:'原始碼', cat:'科技'},
    {en:'bug fix', zh:'錯誤修正', cat:'科技'},
    {en:'search engine', zh:'搜尋引擎', cat:'科技'},

    // 健康
    {en:'balanced diet', zh:'均衡飲食', cat:'健康'},
    {en:'physical exam', zh:'體檢', cat:'健康'},
    {en:'high blood pressure', zh:'高血壓', cat:'健康'},
    {en:'side effect', zh:'副作用', cat:'健康'},
    {en:'stay fit', zh:'保持健康', cat:'健康'},
    {en:'lose weight', zh:'減重', cat:'健康'},
    {en:'mental health', zh:'心理健康', cat:'健康'},
    {en:'cardio exercise', zh:'有氧運動', cat:'健康'},
    {en:'warm up', zh:'暖身', cat:'健康'},
    {en:'get enough sleep', zh:'獲得充足睡眠', cat:'健康'},

    // 情緒
    {en:'in high spirits', zh:'情緒高昂', cat:'情緒'},
    {en:'feel down', zh:'感到沮喪', cat:'情緒'},
    {en:'lost for words', zh:'語塞', cat:'情緒'},
    {en:'calm down', zh:'冷靜下來', cat:'情緒'},
    {en:'burst into tears', zh:'掉下眼淚', cat:'情緒'},
    {en:'over the moon', zh:'欣喜若狂', cat:'情緒'},
    {en:'sick and tired', zh:'厭煩', cat:'情緒'},
    {en:'beside oneself', zh:'極度激動', cat:'情緒'},
    {en:'take a deep breath', zh:'深呼吸', cat:'情緒'},
    {en:'keep one\'s cool', zh:'保持冷靜', cat:'情緒'},

    // 日常
    {en:'wake up', zh:'起床', cat:'日常'},
    {en:'do the dishes', zh:'洗碗', cat:'日常'},
    {en:'rush hour', zh:'尖峰時刻', cat:'日常'},
    {en:'run errands', zh:'辦雜事', cat:'日常'},
    {en:'take out the trash', zh:'倒垃圾', cat:'日常'},
    {en:'hang out', zh:'閒晃', cat:'日常'},
    {en:'pay the bills', zh:'支付帳單', cat:'日常'},
    {en:'get ready', zh:'準備好', cat:'日常'},
    {en:'clean up', zh:'大掃除', cat:'日常'},
    {en:'catch up', zh:'敘舊', cat:'日常'},

    // 購物
    {en:'buy one get one free', zh:'買一送一', cat:'購物'},
    {en:'on sale', zh:'特價中', cat:'購物'},
    {en:'out of stock', zh:'缺貨', cat:'購物'},
    {en:'pay in cash', zh:'現金支付', cat:'購物'},
    {en:'credit card', zh:'信用卡', cat:'購物'},
    {en:'shopping spree', zh:'瘋狂購物', cat:'購物'},
    {en:'clear the balance', zh:'結清餘額', cat:'購物'},
    {en:'window shopping', zh:'純逛不買', cat:'購物'},
    {en:'store credit', zh:'店內購物金', cat:'購物'},
    {en:'final clearance', zh:'出清特賣', cat:'購物'},

    // 天氣
    {en:'heavy rain', zh:'大雨', cat:'天氣'},
    {en:'clear sky', zh:'晴空', cat:'天氣'},
    {en:'freezing cold', zh:'嚴寒', cat:'天氣'},
    {en:'scorching hot', zh:'酷熱', cat:'天氣'},
    {en:'weather forecast', zh:'天氣預報', cat:'天氣'},
    {en:'chance of rain', zh:'降雨機率', cat:'天氣'},
    {en:'global warming', zh:'全球暖化', cat:'天氣'},
    {en:'high pressure', zh:'高氣壓', cat:'天氣'},
    {en:'UV index', zh:'紫外線指數', cat:'天氣'},
    {en:'mild weather', zh:'氣候溫和', cat:'天氣'},

    // 娛樂
    {en:'box office', zh:'售票處', cat:'娛樂'},
    {en:'red carpet', zh:'紅地毯', cat:'娛樂'},
    {en:'live broadcast', zh:'直播', cat:'娛樂'},
    {en:'main character', zh:'主角', cat:'娛樂'},
    {en:'sold out', zh:'售完', cat:'娛樂'},
    {en:'season finale', zh:'本季完結篇', cat:'娛樂'},
    {en:'backstage pass', zh:'後台通行證', cat:'娛樂'},
    {en:'theme song', zh:'主題曲', cat:'娛樂'},
    {en:'special effects', zh:'特效', cat:'娛樂'},
    {en:'binge watch', zh:'連續追劇', cat:'娛樂'},

    // 運動
    {en:'personal best', zh:'個人最佳紀錄', cat:'運動'},
    {en:'world record', zh:'世界紀錄', cat:'運動'},
    {en:'team spirit', zh:'團隊精神', cat:'運動'},
    {en:'half time', zh:'中場休息', cat:'運動'},
    {en:'extra time', zh:'延長賽', cat:'運動'},
    {en:'warm-up exercise', zh:'暖身運動', cat:'運動'},
    {en:'home game', zh:'主場比賽', cat:'運動'},
    {en:'fitness center', zh:'健身中心', cat:'運動'},
    {en:'runner-up', zh:'亞軍', cat:'運動'},
    {en:'gold medal', zh:'金牌', cat:'運動'},

    // 教育
    {en:'higher education', zh:'高等教育', cat:'教育'},
    {en:'final exam', zh:'期末考', cat:'教育'},
    {en:'group project', zh:'小組專案', cat:'教育'},
    {en:'study abroad', zh:'出國留學', cat:'教育'},
    {en:'academic performance', zh:'學業表現', cat:'教育'},
    {en:'office hours', zh:'諮詢時間', cat:'教育'},
    {en:'credit hours', zh:'學分數', cat:'教育'},
    {en:'peer review', zh:'同儕審查', cat:'教育'},
    {en:'deadline extension', zh:'延期截止', cat:'教育'},
    {en:'distance learning', zh:'遠距教學', cat:'教育'},

    // 職場
    {en:'annual bonus', zh:'年終獎金', cat:'職場'},
    {en:'sick leave', zh:'病假', cat:'職場'},
    {en:'paid time off', zh:'有薪假', cat:'職場'},
    {en:'career path', zh:'職涯發展', cat:'職場'},
    {en:'job vacancy', zh:'職缺', cat:'職場'},
    {en:'work from home', zh:'在家工作', cat:'職場'},
    {en:'performance review', zh:'績效評估', cat:'職場'},
    {en:'team meeting', zh:'團隊會議', cat:'職場'},
    {en:'business trip', zh:'出差', cat:'職場'},
    {en:'probationary period', zh:'試用期', cat:'職場'},

    // 環境
    {en:'climate change', zh:'氣候變遷', cat:'環境'},
    {en:'carbon footprint', zh:'碳足跡', cat:'環境'},
    {en:'renewable energy', zh:'可再生能源', cat:'環境'},
    {en:'greenhouse gas', zh:'溫室氣體', cat:'環境'},
    {en:'waste management', zh:'廢棄物管理', cat:'環境'},
    {en:'zero waste', zh:'零廢棄', cat:'環境'},
    {en:'natural disaster', zh:'自然災害', cat:'環境'},
    {en:'environmental protection', zh:'環保', cat:'環境'},
    {en:'fossil fuels', zh:'化石燃料', cat:'環境'},
    {en:'marine life', zh:'海洋生物', cat:'環境'}
  ],
  sentence: [
    // 旅遊
    {en:'Could you show me the way to the gate?', zh:'您能指引我去登機門的路嗎？', cat:'旅遊'},
    {en:'Where can I claim my baggage?', zh:'我在哪裡可以領取行李？', cat:'旅遊'},
    {en:'I would like to make a room reservation.', zh:'我想要預訂房間。', cat:'旅遊'},
    {en:'Is there a shuttle bus to the airport?', zh:'有到機場的接駁巴士嗎？', cat:'旅遊'},
    {en:'What time is check-out tomorrow morning?', zh:'明天早上的退房時間是幾點？', cat:'旅遊'},
    {en:'Excuse me, where is the nearest subway station?', zh:'請問最近的捷運站在哪裡？', cat:'旅遊'},
    {en:'Can I get a tax refund for this item?', zh:'這個商品可以退稅嗎？', cat:'旅遊'},

    // 美食
    {en:'Could we get the menu, please?', zh:'請給我菜單好嗎？', cat:'美食'},
    {en:'Are you ready to order now?', zh:'您準備好點餐了嗎？', cat:'美食'},
    {en:'What do you recommend for dinner?', zh:'晚餐你推薦什麼？', cat:'美食'},
    {en:'Could I have the bill, please?', zh:'請幫我結帳好嗎？', cat:'美食'},
    {en:'Is this dish spicy?', zh:'這道菜會辣嗎？', cat:'美食'},
    {en:'I am allergic to peanuts.', zh:'我對花生過敏。', cat:'美食'},
    {en:'Everything was absolutely delicious.', zh:'每道菜都非常美味。', cat:'美食'},

    // 科技
    {en:'Please restart your system after updating.', zh:'更新後請重新啟動系統。', cat:'科技'},
    {en:'The internet connection is unstable today.', zh:'今天的網路連線不太穩定。', cat:'科技'},
    {en:'You need to enter your password to sign in.', zh:'你需要輸入密碼才能登入。', cat:'科技'},
    {en:'How do I backup my data to the cloud?', zh:'我該如何把資料備份到雲端？', cat:'科技'},
    {en:'This application supports multiple platforms.', zh:'這個應用程式支援多個平台。', cat:'科技'},
    {en:'Artificial intelligence is changing our daily lives.', zh:'人工智慧正在改變我們的日常生活。', cat:'科技'},
    {en:'Make sure to clear your browser cache.', zh:'請確保清除瀏覽器快取。', cat:'科技'},

    // 健康
    {en:'You should drink plenty of water every day.', zh:'你每天應該多喝水。', cat:'健康'},
    {en:'I have been feeling dizzy since this morning.', zh:'我從今天早上開始感到頭暈。', cat:'健康'},
    {en:'Regular exercise helps reduce mental stress.', zh:'定期運動有助於減輕心理壓力。', cat:'健康'},
    {en:'Make sure to take your medicine after meals.', zh:'請務必在飯後服藥。', cat:'健康'},
    {en:'How often do you work out at the gym?', zh:'你多久去一次健身房運動？', cat:'健康'},
    {en:'Eating fresh vegetables promotes good health.', zh:'多吃新鮮蔬菜促進身體健康。', cat:'健康'},
    {en:'I need to schedule an appointment with the doctor.', zh:'我需要預約看醫生。', cat:'健康'},

    // 情緒
    {en:'I am so thrilled about the good news!', zh:'對於這個好消息我感到非常激動！', cat:'情緒'},
    {en:'Take a deep breath when you feel overwhelmed.', zh:'當你感到吃不消時，深呼吸一下。', cat:'情緒'},
    {en:'She expressed her heartfelt gratitude to everyone.', zh:'她向大家表達了由衷的感激。', cat:'情緒'},
    {en:'Don\'t let temporary setbacks affect your confidence.', zh:'不要讓暫時的挫折影響你的信心。', cat:'情緒'},
    {en:'It is completely normal to feel anxious before a speech.', zh:'在演講前感到焦慮是完全正常的。', cat:'情緒'},
    {en:'Seeing his friends again brightened his mood.', zh:'再次見到朋友讓他的心情變好了。', cat:'情緒'},
    {en:'I felt relieved after finishing the project.', zh:'完成專案後我鬆了一口氣。', cat:'情緒'},

    // 日常
    {en:'I usually wake up at seven o\'clock in the morning.', zh:'我通常在早上七點起床。', cat:'日常'},
    {en:'Don\'t forget to turn off the lights before leaving.', zh:'離開前別忘了關燈。', cat:'日常'},
    {en:'The traffic during rush hour is always heavy.', zh:'尖峰時刻的交通總是擁擠。', cat:'日常'},
    {en:'I need to run a few errands this afternoon.', zh:'我今天下午需要辦幾件雜事。', cat:'日常'},
    {en:'Could you help me carry these heavy packages?', zh:'你能幫我搬這些重的包裹嗎？', cat:'日常'},
    {en:'It is important to maintain a healthy routine.', zh:'維持健康的生活作息很重要。', cat:'日常'},
    {en:'What are your plans for the upcoming weekend?', zh:'你這個週末有什麼打算？', cat:'日常'},

    // 購物
    {en:'Is this item currently on sale?', zh:'這個商品目前有特價嗎？', cat:'購物'},
    {en:'Can I try this shirt on in the fitting room?', zh:'我可以在試衣間試穿這件襯衫嗎？', cat:'購物'},
    {en:'Do you accept credit cards or only cash?', zh:'你們接受信用卡還是只收現金？', cat:'購物'},
    {en:'Please keep your receipt in case you need a refund.', zh:'請保留收據以備退款之需。', cat:'購物'},
    {en:'This item is out of stock until next week.', zh:'這項商品缺貨要到下週才有。', cat:'購物'},
    {en:'Can I get a discount if I buy three?', zh:'如果我買三個可以算便宜一點嗎？', cat:'購物'},
    {en:'Where can I find the fitting rooms?', zh:'試衣間在哪裡？', cat:'購物'},

    // 天氣
    {en:'What is the weather forecast for tomorrow?', zh:'明天的天氣預報如何？', cat:'天氣'},
    {en:'It looks like it is going to rain soon.', zh:'看起來快要下雨了。', cat:'天氣'},
    {en:'The temperature has dropped significantly tonight.', zh:'今晚溫度大幅下降。', cat:'天氣'},
    {en:'Remember to bring an umbrella when you go out.', zh:'出門記得帶傘。', cat:'天氣'},
    {en:'It is scorching hot outside today.', zh:'今天外面真是酷熱難耐。', cat:'天氣'},
    {en:'The sky cleared up after the storm passed.', zh:'暴風雨過後天空放晴了。', cat:'天氣'},
    {en:'Humidity is very high during the summer season.', zh:'夏季的濕度非常高。', cat:'天氣'},

    // 娛樂
    {en:'The tickets for the concert were sold out in minutes.', zh:'演唱會門票在幾分鐘內就售罄了。', cat:'娛樂'},
    {en:'Have you seen the latest episode of this series?', zh:'你看過這部影集的最新一集了嗎？', cat:'娛樂'},
    {en:'The movie received great reviews from critics.', zh:'這部電影獲得影評人的一致好評。', cat:'娛樂'},
    {en:'I enjoy listening to live music on weekends.', zh:'我喜歡在週末聽現場音樂。', cat:'娛樂'},
    {en:'Which genre of movies do you prefer watching?', zh:'你偏好看哪種類型的電影？', cat:'娛樂'},
    {en:'The museum is hosting a new art exhibition.', zh:'這間博物館正在舉辦新的藝術展覽。', cat:'娛樂'},
    {en:'The actor gave a brilliant performance in the film.', zh:'這位演員在電影中展現了精彩的演出。', cat:'娛樂'},

    // 運動
    {en:'The team won the championship game last night.', zh:'該隊在昨晚的冠軍賽中獲勝。', cat:'運動'},
    {en:'She set a new world record in swimming.', zh:'她創下了新的游泳世界紀錄。', cat:'運動'},
    {en:'Regular practice is key to improving performance.', zh:'定期練習是提升表現的關鍵。', cat:'運動'},
    {en:'The referee stopped the match due to bad weather.', zh:'裁判因惡劣天氣中止了比賽。', cat:'運動'},
    {en:'He is training hard for the upcoming marathon.', zh:'他正為即將到來的馬拉松努力訓練。', cat:'運動'},
    {en:'Both teams showed great sportsmanship throughout the game.', zh:'兩隊在整場比賽中都展現了極佳的運動家精神。', cat:'運動'},
    {en:'Who do you think will win the match today?', zh:'你認為今天誰會贏得比賽？', cat:'運動'},

    // 教育
    {en:'She applied for a scholarship to study abroad.', zh:'她申請了獎學金打算出國留學。', cat:'教育'},
    {en:'The professor posted the syllabus on the website.', zh:'教授已將課程大綱發布在網站上。', cat:'教育'},
    {en:'Students must submit their assignments by Friday.', zh:'學生必須在週五前繳交作業。', cat:'教育'},
    {en:'He spent the entire night preparing for the exam.', zh:'他花了一整晚時間準備考試。', cat:'教育'},
    {en:'The library offers quiet space for studying.', zh:'圖書館提供安靜的自習空間。', cat:'教育'},
    {en:'Graduation ceremony will take place next month.', zh:'畢業典禮將於下個月舉行。', cat:'教育'},
    {en:'Group projects encourage teamwork and collaboration.', zh:'小組專案能鼓勵團隊合作。', cat:'教育'},

    // 職場
    {en:'We need to complete this project before the deadline.', zh:'我們需要在截止日期前完成這個專案。', cat:'職場'},
    {en:'Please submit your weekly status report by noon.', zh:'請在中午前提交您的每週進度報告。', cat:'職場'},
    {en:'She received a promotion after leading the successful project.', zh:'她在主導成功專案後獲得了升遷。', cat:'職場'},
    {en:'The manager scheduled a team meeting for tomorrow morning.', zh:'經理安排了明天早上的團隊會議。', cat:'職場'},
    {en:'I am writing to apply for the position advertised.', zh:'我寫信應徵貴公司刊登的職缺。', cat:'職場'},
    {en:'Constructive feedback helps employees improve performance.', zh:'建設性的回饋有助於員工提升表現。', cat:'職場'},
    {en:'Working from home offers flexible working hours.', zh:'在家工作提供了彈性的工作時間。', cat:'職場'},

    // 環境
    {en:'Reducing plastic consumption helps protect ocean life.', zh:'減少塑膠使用量有助於保護海洋生物。', cat:'環境'},
    {en:'Solar energy is a clean and renewable resource.', zh:'太陽能是一種清潔且可再生的資源。', cat:'環境'},
    {en:'Climate change affects ecosystems around the globe.', zh:'氣候變遷影響全球的生態系統。', cat:'環境'},
    {en:'Sorting your household trash makes recycling effective.', zh:'對居家垃圾進行分類能使回收更有成效。', cat:'環境'},
    {en:'We must take action to lower carbon emissions.', zh:'我們必須採取行動降低碳排放。', cat:'環境'},
    {en:'Deforestation threatens the natural habitat of wild animals.', zh:'砍伐森林威脅野生動物的天然棲息地。', cat:'環境'},
    {en:'Sustainable practice preserves resources for future generations.', zh:'永續的做法能為後代子孫保存資源。', cat:'環境'}
  ]
};
